### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by yosbelms** [openAVproductions/openAV-Luppp#308]
Could be nice if there is Flatpak package available in Flathub bundling also artyfx.

**Comment by wvengen** [comment]
I have a prototype that seems to launch Luppp. Will see if I find the time to finish and submit it.

<details>

```yaml
id: com.openavproductions.luppp
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk

command: luppp
separate-locales: false
finish-args:
  # X11
  - --share=ipc
  - --socket=x11
  - --device=dri
  # audio: pulseaudio, JACK over PipeWire
  - --socket=pulseaudio
  - --filesystem=xdg-run/pipewire-0

modules:
  - shared-modules/linux-audio/liblo-static.json

  - name: ntk
    buildsystem: simple
    build-commands:
      - python3 waf configure --prefix=${FLATPAK_DEST} --libdir=lib
      - python3 waf
      - python3 waf install
    cleanup:
      - /lib/pkgconfig
      - /lib/*.a
      - /lib/*.a.*
      - /include
      - /bin
    sources:
      - type: archive
        dest-filename: ntk.tar.gz
        url: https://api.github.com/repos/falkTX/ntk/tarball/v1.3.1001
        sha256: 2783e88bc78b4f5d91ef01edbb0ed554189764eacf919d89b6c8a30f6114a4de
        x-checker-data:
          type: json
          url: https://api.github.com/repos/falkTX/ntk/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .tarball_url

  - name: luppp
    buildsystem: simple
    build-commands:
      - meson build --prefix=${FLATPAK_DEST}
      - ninja -C build
      - cd build && meson install
    sources:
      - type: archive
        dest-filename: luppp.tar.gz
        url: https://api.github.com/repos/openAVproductions/openAV-luppp/tarball/release-1.2.1
        sha256: 43bef53e9e388009f63a45f05d870a2a6461b59e721796393bf684cc0cf01bd1
        x-checker-data:
          type: json
          url: https://api.github.com/repos/openAVproductions/openAV-luppp/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .tarball_url
````

</details>
